(() => {
  'use strict';
  const MAX_BYTES=1024*1024,MAX_NODES=2000,MAX_DEPTH=32,MAX_COMMANDS=50000;
  const ALLOWED=new Set(['svg','g','path','rect','circle','ellipse','line','polyline','polygon']);
  const FORBIDDEN=new Set(['script','style','text','foreignobject','image','use','defs','lineargradient','radialgradient','pattern','filter','mask','clippath','animate','animatetransform','set']);
  const ATTRS=new Set(['xmlns','viewbox','width','height','x','y','x1','y1','x2','y2','cx','cy','r','rx','ry','d','points','transform','fill','fill-rule','stroke','stroke-width','opacity','fill-opacity','stroke-opacity','stroke-dasharray','stroke-linecap','stroke-linejoin']);
  const I=[1,0,0,1,0,0],mul=(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]],pt=(m,p)=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]});
  const num=(value,fallback=0)=>{const n=Number(String(value??'').replace(/px$/i,''));return Number.isFinite(n)?n:fallback;};
  const opacity=value=>Math.max(0,Math.min(1,num(value,1)));
  const color=(value,fallback)=>{const v=String(value??fallback??'').trim();if(!v)return fallback;if(/^url\s*\(/i.test(v)||/[;{}]/.test(v))throw new Error('SVG 包含不支持的颜色或外部资源。');return v;};
  function transform(text){let out=I;const source=String(text||'').trim();if(!source)return out;const re=/([a-zA-Z]+)\s*\(([^)]*)\)/g;let match,last=0;while((match=re.exec(source))){if(source.slice(last,match.index).trim())throw new Error('SVG transform 格式无效。');last=re.lastIndex;const name=match[1].toLowerCase(),v=match[2].trim().split(/[\s,]+/).filter(Boolean).map(Number);if(v.some(n=>!Number.isFinite(n)))throw new Error('SVG transform 含无效数值。');let m;if(name==='matrix'&&v.length===6)m=v;else if(name==='translate'&&(v.length===1||v.length===2))m=[1,0,0,1,v[0],v[1]||0];else if(name==='scale'&&(v.length===1||v.length===2))m=[v[0],0,0,v[1]??v[0],0,0];else if(name==='rotate'&&(v.length===1||v.length===3)){const a=v[0]*Math.PI/180,c=Math.cos(a),s=Math.sin(a),r=[c,s,-s,c,0,0];m=v.length===3?mul([1,0,0,1,v[1],v[2]],mul(r,[1,0,0,1,-v[1],-v[2]])):r;}else if(name==='skewx'&&v.length===1)m=[1,0,Math.tan(v[0]*Math.PI/180),1,0,0];else if(name==='skewy'&&v.length===1)m=[1,Math.tan(v[0]*Math.PI/180),0,1,0,0];else throw new Error(`SVG transform ${match[1]} 不受支持。`);out=mul(out,m);}if(source.slice(last).trim())throw new Error('SVG transform 格式无效。');return out;}
  const cloneStyle=s=>({...s});
  function styleFor(node,parent){const s=cloneStyle(parent);if(node.hasAttribute('fill'))s.fill=color(node.getAttribute('fill'),'none');if(node.hasAttribute('fill-rule')){const v=node.getAttribute('fill-rule').trim().toLowerCase();if(!['evenodd','nonzero'].includes(v))throw new Error('SVG fill-rule 不受支持。');s.fillRule=v;}if(node.hasAttribute('stroke'))s.stroke=color(node.getAttribute('stroke'),'none');if(node.hasAttribute('stroke-width'))s.size=Math.max(.1,num(node.getAttribute('stroke-width'),1));if(node.hasAttribute('opacity'))s.opacity*=opacity(node.getAttribute('opacity'));if(node.hasAttribute('fill-opacity'))s.fillOpacity*=opacity(node.getAttribute('fill-opacity'));if(node.hasAttribute('stroke-opacity'))s.strokeOpacity*=opacity(node.getAttribute('stroke-opacity'));if(node.hasAttribute('stroke-dasharray')){const raw=node.getAttribute('stroke-dasharray').trim();if(raw&&raw!=='none'){const vals=raw.split(/[\s,]+/).map(Number);if(vals.some(v=>!Number.isFinite(v)||v<0))throw new Error('SVG 虚线格式无效。');s.dashArray=vals;}else s.dashArray=[];}if(node.hasAttribute('stroke-linecap')){const v=node.getAttribute('stroke-linecap');if(!['butt','round','square'].includes(v))throw new Error('SVG stroke-linecap 不受支持。');s.linecap=v;}if(node.hasAttribute('stroke-linejoin')){const v=node.getAttribute('stroke-linejoin');if(!['miter','round','bevel'].includes(v))throw new Error('SVG stroke-linejoin 不受支持。');s.linejoin=v;}return s;}
  const N=(x,y)=>({x,y});
  function pathFromPoints(points,closed=false){return {closed,nodes:points.map(p=>N(p.x,p.y))};}
  function cubicNode(end,c1,c2,prev){if(prev)prev.out=N(c1.x,c1.y);return {...N(end.x,end.y),in:N(c2.x,c2.y)};}
  function quadraticAsCubic(a,q,b){return [{x:a.x+2*(q.x-a.x)/3,y:a.y+2*(q.y-a.y)/3},{x:b.x+2*(q.x-b.x)/3,y:b.y+2*(q.y-b.y)/3}];}
  function arcPoints(a,rx,ry,rot,large,sweep,b){
    rx=Math.abs(rx);ry=Math.abs(ry);if(!rx||!ry||(!Number.isFinite(rx*ry)))return[b];const phi=rot*Math.PI/180,cp=Math.cos(phi),sp=Math.sin(phi),dx=(a.x-b.x)/2,dy=(a.y-b.y)/2,xp=cp*dx+sp*dy,yp=-sp*dx+cp*dy,lambda=xp*xp/(rx*rx)+yp*yp/(ry*ry);if(lambda>1){const k=Math.sqrt(lambda);rx*=k;ry*=k;}const sign=large===sweep?-1:1,numv=Math.max(0,rx*rx*ry*ry-rx*rx*yp*yp-ry*ry*xp*xp),den=rx*rx*yp*yp+ry*ry*xp*xp,coef=den?sign*Math.sqrt(numv/den):0,cxp=coef*(rx*yp/ry),cyp=coef*(-ry*xp/rx),cx=cp*cxp-sp*cyp+(a.x+b.x)/2,cy=sp*cxp+cp*cyp+(a.y+b.y)/2,angle=(ux,uy,vx,vy)=>{const d=ux*vx+uy*vy,l=Math.hypot(ux,uy)*Math.hypot(vx,vy),c=Math.max(-1,Math.min(1,l?d/l:1));return (ux*vy-uy*vx<0?-1:1)*Math.acos(c);},ux=(xp-cxp)/rx,uy=(yp-cyp)/ry,vx=(-xp-cxp)/rx,vy=(-yp-cyp)/ry,start=angle(1,0,ux,uy);let delta=angle(ux,uy,vx,vy);if(!sweep&&delta>0)delta-=Math.PI*2;if(sweep&&delta<0)delta+=Math.PI*2;const steps=Math.max(4,Math.min(64,Math.ceil(Math.abs(delta)/(Math.PI/12)))),out=[];for(let i=1;i<=steps;i++){const t=start+delta*i/steps,ct=Math.cos(t),st=Math.sin(t);out.push({x:cx+cp*rx*ct-sp*ry*st,y:cy+sp*rx*ct+cp*ry*st});}return out;
  }
  function parsePath(d){
    const tokens=String(d||'').match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?/g)||[];let i=0,cmd='',count=0,current=N(0,0),start=N(0,0),lastC=null,lastQ=null,path=null;const paths=[];const isCmd=t=>/^[a-zA-Z]$/.test(t),read=()=>{const n=Number(tokens[i++]);if(!Number.isFinite(n))throw new Error('SVG path 数值无效。');return n;},ensure=()=>{if(!path){path={closed:false,nodes:[N(current.x,current.y)]};paths.push(path);}return path;},point=(rel,x,y)=>N(rel?current.x+x:x,rel?current.y+y:y);
    while(i<tokens.length){if(isCmd(tokens[i]))cmd=tokens[i++];if(!cmd)throw new Error('SVG path 缺少命令。');const rel=cmd===cmd.toLowerCase(),op=cmd.toUpperCase();if(++count>MAX_COMMANDS)throw new Error('SVG path 命令过多。');
      if(op==='M'){const p=point(rel,read(),read());current=p;start=N(p.x,p.y);path={closed:false,nodes:[N(p.x,p.y)]};paths.push(path);cmd=rel?'l':'L';lastC=lastQ=null;continue;}
      ensure();if(op==='Z'){path.closed=true;current=N(start.x,start.y);path=null;cmd='';lastC=lastQ=null;continue;}
      if(op==='L'||op==='H'||op==='V'){const p=op==='L'?point(rel,read(),read()):op==='H'?N(rel?current.x+read():read(),current.y):N(current.x,rel?current.y+read():read());path.nodes.push(N(p.x,p.y));current=p;lastC=lastQ=null;continue;}
      if(op==='C'){const c1=point(rel,read(),read()),c2=point(rel,read(),read()),p=point(rel,read(),read()),node=cubicNode(p,c1,c2,path.nodes.at(-1));path.nodes.push(node);current=p;lastC=c2;lastQ=null;continue;}
      if(op==='S'){const c1=lastC?N(2*current.x-lastC.x,2*current.y-lastC.y):N(current.x,current.y),c2=point(rel,read(),read()),p=point(rel,read(),read()),node=cubicNode(p,c1,c2,path.nodes.at(-1));path.nodes.push(node);current=p;lastC=c2;lastQ=null;continue;}
      if(op==='Q'||op==='T'){const q=op==='Q'?point(rel,read(),read()):(lastQ?N(2*current.x-lastQ.x,2*current.y-lastQ.y):N(current.x,current.y)),p=point(rel,read(),read()),[c1,c2]=quadraticAsCubic(current,q,p),node=cubicNode(p,c1,c2,path.nodes.at(-1));path.nodes.push(node);current=p;lastQ=q;lastC=c2;continue;}
      if(op==='A'){const rx=read(),ry=read(),rot=read(),large=!!read(),sweep=!!read(),p=point(rel,read(),read());for(const q of arcPoints(current,rx,ry,rot,large,sweep,p))path.nodes.push(N(q.x,q.y));current=p;lastC=lastQ=null;continue;}
      throw new Error(`SVG path 命令 ${cmd} 不受支持。`);
    }
    return paths.filter(p=>p.nodes.length>0);
  }
  function shapePaths(node){const t=node.localName.toLowerCase(),x=num(node.getAttribute('x')),y=num(node.getAttribute('y'));if(t==='path')return parsePath(node.getAttribute('d'));
    if(t==='line')return[pathFromPoints([N(num(node.getAttribute('x1')),num(node.getAttribute('y1'))),N(num(node.getAttribute('x2')),num(node.getAttribute('y2')))])];
    if(t==='polyline'||t==='polygon'){const vals=(node.getAttribute('points')||'').trim().split(/[\s,]+/).filter(Boolean).map(Number);if(vals.length<4||vals.length%2||vals.some(v=>!Number.isFinite(v)))throw new Error('SVG points 无效。');const pts=[];for(let i=0;i<vals.length;i+=2)pts.push(N(vals[i],vals[i+1]));return[pathFromPoints(pts,t==='polygon')];}
    if(t==='rect'){const w=num(node.getAttribute('width')),h=num(node.getAttribute('height'));if(w<0||h<0)throw new Error('SVG rect 尺寸无效。');const rx=Math.min(Math.abs(num(node.getAttribute('rx'),num(node.getAttribute('ry'),0))),w/2),ry=Math.min(Math.abs(num(node.getAttribute('ry'),rx)),h/2);if(!rx&&!ry)return[pathFromPoints([N(x,y),N(x+w,y),N(x+w,y+h),N(x,y+h)],true)];const k=.5522847498,p={closed:true,nodes:[N(x+rx,y),N(x+w-rx,y),N(x+w,y+ry),N(x+w,y+h-ry),N(x+w-rx,y+h),N(x+rx,y+h),N(x,y+h-ry),N(x,y+ry)]};const n=p.nodes,n0=n.length;for(let i=0;i<n0;i++){const a=n[i],b=n[(i+1)%n0];if(i%2===1){const horizontal=Math.abs(a.y-b.y)<1e-6;if(horizontal){const dir=Math.sign(b.x-a.x);a.out=N(a.x+dir*rx*k,a.y);b.in=N(b.x-dir*rx*k,b.y);}else{const dir=Math.sign(b.y-a.y);a.out=N(a.x,a.y+dir*ry*k);b.in=N(b.x,b.y-dir*ry*k);}}}return[p];}
    const cx=num(node.getAttribute('cx')),cy=num(node.getAttribute('cy')),rx=t==='circle'?Math.abs(num(node.getAttribute('r'))):Math.abs(num(node.getAttribute('rx'))),ry=t==='circle'?rx:Math.abs(num(node.getAttribute('ry')));if((t==='circle'||t==='ellipse')&&rx>=0&&ry>=0){const k=.5522847498,p={closed:true,nodes:[N(cx+rx,cy),N(cx,cy+ry),N(cx-rx,cy),N(cx,cy-ry)]};p.nodes[0].out=N(cx+rx,cy+k*ry);p.nodes[1].in=N(cx+k*rx,cy+ry);p.nodes[1].out=N(cx-k*rx,cy+ry);p.nodes[2].in=N(cx-rx,cy+k*ry);p.nodes[2].out=N(cx-rx,cy-k*ry);p.nodes[3].in=N(cx-k*rx,cy-ry);p.nodes[3].out=N(cx+k*rx,cy-ry);p.nodes[0].in=N(cx+rx,cy-k*ry);return[p];}
    return[];
  }
  function applyMatrix(paths,m){return paths.map(path=>({...path,nodes:path.nodes.map(node=>{const p=pt(m,node),out={...node,x:p.x,y:p.y};if(node.in)out.in=pt(m,node.in);if(node.out)out.out=pt(m,node.out);return out;})}));}
  function elementFrom(node,style,m,newId){const paths=applyMatrix(shapePaths(node),m);if(!paths.length)return null;const stroke=style.stroke&&style.stroke!=='none'?'solid':'none',fill=style.fill&&style.fill!=='none'?'solid':'none',scale=Math.sqrt(Math.abs(m[0]*m[3]-m[1]*m[2]))||1;return{id:newId(),type:'path',paths,color:fill!=='none'?style.fill:(stroke!=='none'?style.stroke:'#000000'),fillColor:style.fill||'#000000',strokeColor:style.stroke||'#000000',fill,fillRule:style.fillRule||'nonzero',stroke,size:(style.size||1)*scale,dash:style.dashArray?.length?'dashed':'solid',dashArray:Array.isArray(style.dashArray)?style.dashArray.map(v=>v*scale):null,linecap:style.linecap||'butt',linejoin:style.linejoin||'miter',opacity:style.opacity,fillOpacity:style.fillOpacity,strokeOpacity:style.strokeOpacity};}
  function parse(text,{newId=()=>`e${Math.random().toString(36).slice(2)}`}={}){
    const source=String(text||'');if(new Blob([source]).size>MAX_BYTES)throw new Error('SVG 超过 1 MiB 安全上限。');if(/<!DOCTYPE|<!ENTITY/i.test(source))throw new Error('SVG 不允许 DOCTYPE 或实体。');
    const doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror'))throw new Error('SVG XML 解析失败。');const root=doc.documentElement;if(root?.localName?.toLowerCase()!=='svg')throw new Error('剪贴板内容不是 SVG。');
    let nodeCount=0,commandCount=0;const elements=[];const base={fill:'#000000',fillRule:'nonzero',stroke:'none',size:1,opacity:1,fillOpacity:1,strokeOpacity:1,dashArray:null,linecap:'butt',linejoin:'miter'};
    const walk=(node,parentStyle,parentMatrix,depth)=>{if(depth>MAX_DEPTH)throw new Error('SVG 嵌套超过 32 层。');if(++nodeCount>MAX_NODES)throw new Error('SVG 节点超过 2000 个。');const tag=node.localName?.toLowerCase();if(FORBIDDEN.has(tag)||!ALLOWED.has(tag))throw new Error(`SVG 元素 <${tag}> 不受支持。`);for(const attr of [...node.attributes]){const name=attr.name.toLowerCase();if(name.startsWith('on')||name==='style'||name==='class'||name==='href'||name==='xlink:href'||!ATTRS.has(name))throw new Error(`SVG 属性 ${attr.name} 不受支持。`);if(/url\s*\(/i.test(attr.value))throw new Error('SVG 外部资源、渐变或滤镜不受支持。');}
      const style=styleFor(node,parentStyle),matrix=mul(parentMatrix,transform(node.getAttribute('transform')));if(tag!=='svg'&&tag!=='g'){const el=elementFrom(node,style,matrix,newId);if(el){commandCount+=el.paths.reduce((sum,p)=>sum+p.nodes.length,0);if(commandCount>MAX_COMMANDS)throw new Error('SVG 归一化路径节点超过 50000。');elements.push(el);}}
      for(const child of [...node.children])walk(child,style,matrix,depth+1);
    };
    let rootMatrix=I;const viewBox=(root.getAttribute('viewBox')||'').trim();if(viewBox){const v=viewBox.split(/[\s,]+/).map(Number);if(v.length!==4||v.some(n=>!Number.isFinite(n))||v[2]<=0||v[3]<=0)throw new Error('SVG viewBox 无效。');const width=num(root.getAttribute('width'),v[2]),height=num(root.getAttribute('height'),v[3]);if(width<=0||height<=0)throw new Error('SVG 尺寸无效。');rootMatrix=mul([width/v[2],0,0,height/v[3],0,0],[1,0,0,1,-v[0],-v[1]]);}
    walk(root,base,rootMatrix,1);if(!elements.length)throw new Error('SVG 中没有可导入的矢量形状。');return{elements,nodeCount,commandCount};
  }
  const api={parse,MAX_BYTES,MAX_NODES,MAX_DEPTH,MAX_COMMANDS};globalThis.QuickdrawSVGImport=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
